@include('includes/header')
@include('includes/menu')

<!-- Page Content -->
<div class="container"><br>
  <div class="col-md-12">
    <center><h3>All the money generated by this website will be donated to animal institutions.</h3></center>
    <br><br>
    <div class="row">
      <div class="col-md-6">
        <h4>Bitcoin</h4>
        <hr></hr>
        <div class="col-md-12">
          <strong>12iffXcH1R8ntqdfFxYBpy7aRmpWLixgeQ</strong>
          <img src="bitcoin.png">
        </div>
      </div>
      <div class="col-md-6">
        <h4>Paypal</h4>
        <hr></hr>
        <div class="row">
          <div class="col-md-12">
            <br><a href="https://www.paypal.me/jsantos22/" target="_blank"><img src="paypal.png"></a>
          </div>

        </div>
      </div>
    </div>
    <br><br>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- TrumpMemes2 -->
  <center><ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-7332385499198715"
       data-ad-slot="4345617271"
       data-ad-format="auto"></ins></center>
  <script>
  (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
    </div>
  </div>
  @include('includes/footer')
